language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip3 install -r deploy/requirements.txt"
  - "pip3 install Fabric"
# command to run tests
script: nosetests

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master