language: python
python:
  - "3.4"

install:
  - "pip3 install -r deploy/requirements.txt"

# command to run tests
script: nosetests

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
