# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0037_auto_20150920_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField()),
                ('action_text_ru', models.TextField()),
                ('action_text_en', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='faucet',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faucethistory',
            name='faucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.Faucet'),
        ),
    ]
